### ISSUE TITLE
Unsupported declare 'strict_types'

### ISSUE THREAD

**Issue by MuhammadSaim** [ramsey/uuid#319] opened 2020-05-15 17:49 UTC
## Parse Error in function.php at 34

Warning: Unsupported declare 'strict_types' in /home/austonadmin/public_html/backOfficeAPI/vendor/ramsey/uuid/src/functions.php on line 14

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/austonadmin/public_html/backOfficeAPI/vendor/ramsey/uuid/src/functions.php on line 34

`function v1($node = null, ?int $clockSeq = null): string
{
    return Uuid::uuid1($node, $clockSeq)->toString();
}`

On the Server PHP version is 7.3.

**Comment by ramsey** [comment] 2020-05-15 18:10
Are you sure you're running PHP 7.3? `strict_types` was added in PHP 7.0.0, and nullable types were added in PHP 7.1.

**Comment by MuhammadSaim** [comment] 2020-05-15 18:48
Yeah Thanks, I just update the PHP version to 7.3, unfortunately, the version was not updated I just look it back and update it again Thanks man

**Comment by goodmuyis** [comment] 2020-05-29 17:48
I have same issue, had to switch PHP version between 7.3 and 7.2 each time i upload a laravel site online

**Comment by ramsey** [comment] 2020-05-29 23:30
Can you provide more details or a reproducible example? I don't know what you mean by "had to switch PHP version."

**Comment by goodmuyis** [comment] 2020-05-30 21:22
> Can you provide more details or a reproducible example? I don't know what you mean by "had to switch PHP version."

I was using [CoreUI](https://github.com/coreui/coreui-free-laravel-admin-template) git clone, running Laravel 7*, PHP 7.2 on my laptop, everything works fine throughout development up till now.

> "had to switch PHP version."

The first I upload site online, it works fine, but the second time I upload update to live site mainly the  following folder App, Database, Public and Resources, it triggered the error above. At first i assumed it was php compatibility so I downgrade php7.2, and the site work fine.

The next update I did (3rd), the error was triggered and switch back to php7.3
The 4th update, i had to switch back to php7.2 which is running the site presciently.

From the _/vendor/ramsey/uuid/CHANGELOG.md_ is should be using the version below
## [4.0.1] - 2020-03-29

**Comment by ramsey** [comment] 2020-05-30 22:37
These are the errors you're seeing?

```
Warning: Unsupported declare 'strict_types' in /home/austonadmin/public_html/backOfficeAPI/vendor/ramsey/uuid/src/functions.php on line 14

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/austonadmin/public_html/backOfficeAPI/vendor/ramsey/uuid/src/functions.php on line 34
```

The only way either of these errors can occur is if you're running PHP 5. The `strict_types` declare statement was introduced in PHP 7.0 and nullable types (the "unexpected '?'" error) were introduced in PHP 7.1.

I want to help get to the bottom of these errors. I know they're not coming from this library, since these are features supported by PHP 7.2 and up.

Can you confirm that the server is running PHP 7.2 or later when you see these errors? Where do you see the errors? Are they printed to the screen when you load a web page? If so, can you verify that the web server is configured to run with the correct version of PHP?

Thanks!

**Comment by goodmuyis** [comment] 2020-06-02 11:47
> These are the errors you're seeing?
> 
> ```
> Warning: Unsupported declare 'strict_types' in /home/austonadmin/public_html/backOfficeAPI/vendor/ramsey/uuid/src/functions.php on line 14
> 
> Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/austonadmin/public_html/backOfficeAPI/vendor/ramsey/uuid/src/functions.php on line 34
> ```
> 
> The only way either of these errors can occur is if you're running PHP 5. The `strict_types` declare statement was introduced in PHP 7.0 and nullable types (the "unexpected '?'" error) were introduced in PHP 7.1.
> 
> I want to help get to the bottom of these errors. I know they're not coming from this library, since these are features supported by PHP 7.2 and up.
> 
> Can you confirm that the server is running PHP 7.2 or later when you see these errors? Where do you see the errors? Are they printed to the screen when you load a web page? If so, can you verify that the web server is configured to run with the correct version of PHP?
> 
> Thanks!

Yes sure am using php7.2, and am getting the error below.

```
PHP Warning:  Unsupported declare 'strict_types' in /home/tahserio/tahseri_app/vendor/ramsey/uuid/src/functions.php on line 14

PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/tahserio/tahseri_app/vendor/ramsey/uuid/src/functions.php on line 34
```
As at this morning, before uploading new update I do confirmed the php version to be 7.2. as soon as i extract the files, the error show up, had to switch the php version to 7.3 to get the site working. 

Offline version of php is 7.2

**Comment by anibabbar** [comment] 2020-06-13 20:15
> > Can you provide more details or a reproducible example? I don't know what you mean by "had to switch PHP version."
> 
> I was using [CoreUI](https://github.com/coreui/coreui-free-laravel-admin-template) git clone, running Laravel 7*, PHP 7.2 on my laptop, everything works fine throughout development up till now.
> 
> > "had to switch PHP version."
> 
> The first I upload site online, it works fine, but the second time I upload update to live site mainly the following folder App, Database, Public and Resources, it triggered the error above. At first i assumed it was php compatibility so I downgrade php7.2, and the site work fine.
> 
> The next update I did (3rd), the error was triggered and switch back to php7.3
> The 4th update, i had to switch back to php7.2 which is running the site presciently.
> 
> From the _/vendor/ramsey/uuid/CHANGELOG.md_ is should be using the version below
> ## [4.0.1] - 2020-03-29

exactly same happening with me !!

**Comment by ramsey** [comment] 2020-06-13 20:42
If you put up a page with `phpinfo()` on it and load that page in your browser, can you confirm that you're running PHP 7.2 or later?

I suspect there might be a difference between the CLI and FPM versions of PHP that you're running. Verifying the version of PHP your web server is using will help me debug this.

**Comment by ramsey** [comment] 2020-06-14 01:41
This issue seems related: https://github.com/stayallive/wp-sentry/issues/46

**Comment by goodmuyis** [comment] 2020-06-17 18:46
> If you put up a page with `phpinfo()` on it and load that page in your browser, can you confirm that you're running PHP 7.2 or later?
> 
> I suspect there might be a difference between the CLI and FPM versions of PHP that you're running. Verifying the version of PHP your web server is using will help me debug this.

**CPanel PHP version:** PHP 7.2 (ea-php72) 

These are details from phpinfo()

**PHP Version** 7.2.29
**Server API**  CGI/FastCGI

**Comment by ramsey** [comment] 2020-06-18 00:31
Is that the version reported from CPanel's `phpinfo()` page, or is that `phpinfo()` in the website where you're having this issue?

**Comment by goodmuyis** [comment] 2020-06-18 19:05
> Is that the version reported from CPanel's `phpinfo()` page, or is that `phpinfo()` in the website where you're having this issue?

The first line is the version i copied from cpanel which the website is running.

The rest that of the out of page that has the phpinfo()

**Comment by sagautam5** [comment] 2020-06-27 13:02
I am having similar issue while making virtual host for my laravel 7 project in "ubantu16.04" with php version "7.3". Little bit confused by comments above.

**Comment by ramsey** [comment] 2020-06-27 16:09
I’m confused by this entire thread. There’s no way to receive these error messages on PHP 7.2+. I have no idea what’s going on. I wish I could reproduce this.

**Comment by sagautam5** [comment] 2020-06-28 04:05
I don't have these issues when I have used php 7.0 and laravel 5 for development. Now, I have a new project in Laravel 7 and php version is 7.3, I have got this error while making virtual host for my project. After making all configurations and domain pointing, A blank white screen is shown up. In the network bar there is 500 internal server error and when I saw apache error log then I saw the Unsupported declare 'strict_types' error when I hit my site url made just before with virtual host.

**Comment by sagautam5** [comment] 2020-06-28 04:05
I don't have these issues when I have used php 7.0 and laravel 5 for development. Now, I have a new project in Laravel 7 and php version is 7.3, I have got this error while making virtual host for my project. After making all configurations and domain pointing, A blank white screen is shown up. In the network bar there is 500 internal server error and when I saw apache error log then I saw the Unsupported declare 'strict_types' error when I hit my site url made just before with virtual host.

**Comment by sagautam5** [comment] 2020-06-28 05:09
I don't have these issues when I have used php 7.0 and laravel 5 for development. Now, I have a new project in Laravel 7 and php version is 7.3, I have got this error while making virtual host for my project. After making all configurations and domain pointing, A blank white screen is shown up. In the network bar there is 500 internal server error and when I saw apache error log then I saw the Unsupported declare 'strict_types' error when I hit my site url made just before with virtual host.

**Comment by goodmuyis** [comment] 2020-06-30 20:47
> I’m confused by this entire thread. There’s no way to receive these error messages on PHP 7.2+. I have no idea what’s going on. I wish I could reproduce this.

Update:
The issue might likely by a mis-configuration from the shared-hosting. Recently I uploaded new update (Same folders and files) as i used to do, there was no 'strict_types' error this time around, and the php configuration still stand at 7.2.

**Comment by StyxOfDynamite** [comment] 2020-07-03 20:01
I keep running into this when switching between PHP versions. This must be the third time this week I've re-read this thread. Seems that sometimes after switching down to 7.0 and then back to 7.4 it doesn't switch cleanly. Usually a restart resolves

**Comment by nikeshhajari** [comment] 2020-07-04 22:56
I only get:

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/vendor/ramsey/uuid/src/functions.php on line 34

I'm running php-apache in a docker container. PHP container is using 

PHP Version 7.0.33


Let me know what else I can provide.

**Comment by riskinurohman** [comment] 2020-07-16 15:16
Just change your php version between 7,2 or 7.3. It works

**Comment by Crouxie** [comment] 2020-10-25 12:01
Same issue here. Using version 7.4.11 (IIS version 6.2) but error is same.
- installed 7.4.11 but same issue
- switched between versions, then restarted -> not working

**Comment by ramsey** [comment] 2020-10-25 16:44
This error only occurs on PHP 5. Check your web server configuration to make sure it is running PHP 7.

Also, if still having these problems, can you please share the contents of your `composer.json` and the full `composer install` or `composer update` command you use when installing your dependencies?

Thanks!

**Comment by Crouxie** [comment] 2020-10-26 13:32
> 
> 
> This error only occurs on PHP 5. Check your web server configuration to make sure it is running PHP 7.
> 
> Also, if still having these problems, can you please share the contents of your `composer.json` and the full `composer install` or `composer update` command you use when installing your dependencies?
> 
> Thanks!

It occured on 2 separate fresh installs (version 7.15.0, 2 different servers) but one thing is same...usage of IIS. I have checked both enviroments with phpinfo() and php was loaded correctly. I really dont know in which moment problem was solved, but I think that it was solved by deleting/adding CGI handler mappings.

**Comment by omusegad** [comment] 2021-04-27 10:08
am also experiencing this issue on fresh laravel setup, local setup works ok once i upload on cpanel server that's when this error pops up

**Comment by ramsey** [comment] 2021-04-27 15:18
Do you have any other scripts running on the server that include `declare(strict_types=1);` at the top?

**Comment by ramsey** [comment] 2022-08-05 17:52
It's been over a year, and I've not heard any more complaints about this issue, so I'm closing it. I suspect this was caused by different versions of PHP running on the system.

**Closed by ramsey** 2022-08-05 17:52 UTC
Labels: bug
