### ISSUE TITLE
Travis times out in builds

### ISSUE THREAD

**Issue by mjrider** [ramsey/uuid#190] opened 2017-10-18 10:11 UTC
Where my local system needs 5 seconds, travis takes 11 minutes and aften abort the build because of that.
Testing where this breaks seems to point to the unittest 'Ramsey\Uuid\Test\UuidTest::test32BitMatch64BitForOneHourPeriod'
on my system this gives a visual slowdown of about  2 seconds, on travis this is +10 minutes

this makes development difficult because PR's get as status that the build is broken, while the the code passes the build.

Suggested fix: manual validate if there it is possible to create a reduction of the 3600*4 iterations the testcase makes. or speedup the math/logic behind it

**Comment by ramsey** [comment] 2017-11-10 22:16
The reason for so many iterations is because early versions of the library had a bug where version 1 UUIDs were not being generated properly, and I was able to reproduce the bug when generating UUIDs for every second within a given hour. This test exists to ensure that the bug is not reintroduced.

That said, I might be able to figure out a way to simplify the test. Also, the time it takes to run the build is substantially reduced in PHP 7+.

**Comment by ramsey** [comment] 2018-07-22 02:55
Closing this issue. The 4.x series requires PHP 7.2 and up, and this is not an issue on PHP 7.

**Closed by ramsey** 2018-07-22 02:55 UTC
Labels: enhancement
